spring.application.name=BackendFilmes

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/filmes}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:filmes}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:filmes}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
